version: "3.9"

services:
  api:
    build: .
    container_name: perspectiva_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: perspectiva_db
    restart: always
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
